use `sql7347782`;

CREATE TABLE azienda(
RAGIONESOCIALE VARCHAR(30),
PARTITAIVA VARCHAR(30),
CF VARCHAR(30),
CITTA VARCHAR(30),
MAIL VARCHAR(30) PRIMARY KEY,
PASSWORD_A VARCHAR(30),
SESSIONE_ID INTEGER,

FOREIGN KEY(SESSIONE_ID) REFERENCES sessione(ID)

);


