
CREATE TABLE conto (
NUMERO_CONTO int(11) primary key,
PROPRIETARIO_AZIENDA varchar(30),
PROPRIETARIO_PERSONA_FISICA varchar(30),
SALDO double,
FOREIGN KEY (PROPRIETARIO_PERSONA_FISICA) REFERENCES cliente (EMAIL),
FOREIGN KEY (PROPRIETARIO_AZIENDA) REFERENCES azienda (MAIL)
);

