
CREATE TABLE movimenti (
ID_MOVIMENTO integer AUTO_INCREMENT,
NUMERO_CONTO_MOVIMENTO int(11),
SOMMA_DENARO double,
VERSANENTO_PRELIEVO varchar(30),
DATA_MOVIMENTO date,
PRIMARY KEY (ID_MOVIMENTO),
FOREIGN KEY (NUMERO_CONTO_MOVIMENTO) REFERENCES conto (NUMERO_CONTO)
);

